name: Build Apk for DEV flavor

on:
  pull_request:
    branches:
      - develop
      - product
  workflow_dispatch:

jobs:
#  analyze:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: echo Install Flutter stable channel Successfully!!
#      - name: Analyze Code and Testing
#        run: |
#          flutter clean
#          flutter pub get
#          flutter pub run build_runner build --delete-conflicting-outputs
#          flutter analyze
#          flutter test

  build:
    runs-on: ubuntu-latest
#    needs: ["analyze"]
    steps:
      - uses: actions/checkout@v2
#       - name: Install Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#       - run: echo Install Flutter stable channel Successfully!!
#       - name: Setup
#         run: |
#           flutter clean
#           flutter pub get
#           flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build DEV
        if: github.base_ref == 'develop'
#         run: flutter build apk --flavor dev -t lib/main_dev.dart
        run: echo dev
      - name: BUILD PROD
        if: github.base_ref == 'product'
        run: echo prod
#       - run: echo Build phase successful!!
#       - name: release
#         uses: actions/upload-artifact@v3
#         with:
#           name: flavoring-dev
#           path: build/app/outputs/flutter-apk/app-dev-release.apk
#       - run: echo Here your apk!!
